name: Build

on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
        build_type: [ Release ]

        include:
          - os: ubuntu
            cc: clang
            cxx: clang++

    runs-on: ${{matrix.os}}-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CC & CXX
        if: matrix.cc != '' && matrix.cxx != ''
        run: echo "CC=${{matrix.cc}}" >> $GITHUB_ENV && echo "CXX=${{matrix.cxx}}++" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ${{matrix.os == 'windows' && format('.\{0}\anitomy_c_test.exe', matrix.build_type) || './anitomy_c_test'}}
